### PR TITLE
Add multiple sounds

### PR DESCRIPTION
**Pull request by Slackadays**
This PR:

- replaces the existing sounds with a luscious FM tubular bell one made by my keyboard
- moves the existing sounds to an `assets` folder where they're available anytime in the future
- includes additional FM vibraphone sounds in case you'd like to use those ones instead

If you prefer that the sounds be different (like different reverb or key) then I can make new ones too

### CODE REVIEW

**Comment by Tanza3D** [comment]
the current sounds are fine to me, i don't see much point in changing them - the tone of yours i feel could probably be more harsh than the one we have right now when spammed alot - i like the idea of letting people choose which sounds they want from a dropdown, but the existing ones should be default

**Comment by Slackadays** [comment]
@Tanza3D Fixed, there is now a selector button with Guitar (the original sound) as the default

**Comment by Tanza3D** [comment]
that js is kind of scuffed, i'd have an array of objects with the private, public, and name, then query that and just up the active index in it (until it overflows then reset back to 0), instead of the wall of if/else

**Comment by Tanza3D** [comment]
```js
const sounds = [
    {
        "name":"Sound name",
        "public":"sound_public.mp3",
        "private":"sound_private.mp3"
    },
    {
        "name":"Another sound name",
        "public":"sound2_public.mp3",
        "private":"sound2_private.mp3"
    }
]
```

**Comment by Tanza3D** [comment]
probably not worth continuing this PR since there seems to be a massive JS overhaul about to come in which would probably require this to be rewritten from the ground up anyway

**Comment by Slackadays** [comment]
would you accept a pr for that rewrite?

**Comment by Slackadays** [comment]
This was actually a quick fix

**Comment by Slackadays** [comment]
Would you be willing to accept this as a trial until the new platform gets shipped? It looks like it's going to be super fancy so it may not come for a bit

**Comment by username-is-required** [comment]
one thing i’d just caution is bearing in mind how this is going to look on mobile. there are already quite a few buttons/options very close to each other, with the limited width of a mobile screen to compete for

IMG_9338

**Comment by rewbycraft** [comment]
I'd be open to accepting a dropdown for sound.
This PR would need to be updated for the current codebase first.
Also, maybe we should to put this dropdown and the "hide subreddit" buttons in a small settings menu?

**Pull request closed without merging**
